import os

GCP_BUCKET_NAME = os.getenv("GCP_BUCKET_NAME")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS")
SCORE_THRESHOLD = int(os.getenv("SCORE_THRESHOLD", 45))
MAX_ITERATIONS = int(os.getenv("MAX_ITERATIONS", 3))
GENAI_MODEL = os.getenv("GENAI_MODEL", "gemini-2.0-flash")
API_DELAY_SECONDS = int(os.getenv("API_DELAY_SECONDS", 5))